name: update-changelog

on:
  release:
    types: [ released ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          path-to-changelog: changelog.md
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update changelog
          file_pattern: changelog.md
